'use client';
import React from 'react';
import { useState, useEffect } from 'react';
import Image, { StaticImageData } from "next/image";
import { useInterface } from '@/components/context/interface-context';
import { useTranslation } from 'react-i18next';
import Base from "../../public/images/nec-section/section-4/base-nec-section-4.webp"
import Slide_Dung from "../../public/images/nec-section/section-4/Slide_Dung.avif"
import Quote from "../../public/images/nec-section/section-4/quote.svg"
import ArrowLeft from "../../public/images/nec-section/section-4/arrow-left.svg"
import ArrowRight from "../../public/images/nec-section/section-4/arrow-right.svg"
import {
    Carousel,
    CarouselContent,
    CarouselItem,
    CarouselPrevious,
    CarouselNext,
} from "@/components/ui/carousel-nec"

const Section4: React.FC = () => {
    const { t } = useTranslation();
    const [current, setCurrent] = useState(0);
    const { isDesktop, isTablet, isMobile } = useInterface();
    const slides = [
        {
            name: 'Lưu Phương Dung',
            role: 'Wealth Farming Investor',
            content1: `"As one of the first people to participate in Wealth Farming, I only hoped for some additional monthly passive income. But what I received was so much more than that."`,
            content2: `Thanks to the stable income from BeQ Holdings' Wealth Farming Fund, my family has been able to purchase our dream home and comfortably pay the bank interest each month without stress, and we even have some financial surplus from the passive income generated by the Wealth Farming Fund.`,
            content3: `I am grateful to the CEO and the BeQ team for creating a credible and sustainable financial solution. If you are looking for a reliable source of passive income, this is a worthwhile option to start with.`,
            image: Slide_Dung,
        },
        {
            name: 'Lưu Phương Dung 2',
            role: 'Wealth Farming Investor',
            content1: `"As one of the first people to participate in Wealth Farming, I only hoped for some additional monthly passive income. But what I received was so much more than that."`,
            content2: `Thanks to the stable income from BeQ Holdings' Wealth Farming Fund, my family has been able to purchase our dream home and comfortably pay the bank interest each month without stress, and we even have some financial surplus from the passive income generated by the Wealth Farming Fund.`,
            content3: `I am grateful to the CEO and the BeQ team for creating a credible and sustainable financial solution. If you are looking for a reliable source of passive income, this is a worthwhile option to start with.`,
            image: Slide_Dung,
        },
    ];


    return (
        <section className="nec-section flex items-center justify-center nec-section-4 relative py-[80px] px-[40px] overflow-x-hidden">
            <Image
                src={Base}
                alt='Base Section 4'
                width={1200}
                height={673}
                className='absolute w-full filter brightness-[0.8] left-0 z-0 top-0 h-full object-cover object-center'
            />
            <div
                className={`${isTablet ? 'w-[80%] h-[407px]' : isMobile ? 'w-[360px] h-[577px]' : 'h-[407px]'} relative max-w-[768px] flex flex-col justify-between flex-shrink-0 z-10`}
            >
                <Carousel className='w-full h-full'>
                    <CarouselContent>
                        {slides.map((slide, index) => (
                            <CarouselItem key={index} className={`h-full flex flex-col gap-[10px] justify-between bg-[var(--base-bg)] p-[40px] mr-2`}>
                                <div className="flex gap-[10px] justify-between">
                                    <div className="flex gap-[16px] items-center">
                                        <div className='w-[60px] rounded-full h-[60px]'>
                                            <Image
                                                src={slide.image}
                                                alt={slide.name}
                                                width={403}
                                                height={555}
                                                className='w-full h-full object-cover object-[46.2%_33.5%] rounded-[inherit]'
                                            />
                                        </div>
                                        <div>
                                            <p className='h4 font-geist-raleway-place-holder'>{t(slide.name)}</p>
                                            <p className='text-[var(--text-light)] text-[12px]'>{t(slide.role)}</p>
                                        </div>
                                    </div>
                                    <div className='flex'>
                                        <Image src={Quote} alt='Quote' width={isMobile ? 24 : 33} height={isMobile ? 40 : 56} />
                                        <Image src={Quote} alt='Quote' width={isMobile ? 24 : 33} height={isMobile ? 40 : 56} />
                                    </div>
                                </div>

                                <div className='flex flex-col gap-[20px]'>
                                    <p className='h3 !font-[600] flex text-center font-geist-raleway-place-holder'>{t(slide.content1)}</p>
                                    <div>
                                        <p className='!text-[12px] flex text-center'>{t(slide.content2)}</p>
                                        <p className='!text-[12px] flex text-center mt-[8px]'>{t(slide.content3)}</p>
                                    </div>
                                </div>
                            </CarouselItem>
                        ))}
                    </CarouselContent>

                    <CarouselPrevious className={`${isMobile ? '-left-[20px]' : '-left-[60px]'} absolute bg-[#00000033] top-1/2 rounded-[40px] cursor-pointer`}>
                        <Image src={ArrowLeft} alt='ArrowLeft' width={40} height={40} />
                    </CarouselPrevious>
                    <CarouselNext className={`${isMobile ? '-right-[20px]' : '-right-[60px]'} absolute bg-[#00000033] top-1/2 rounded-[40px] cursor-pointer`}>
                        <Image src={ArrowRight} alt='ArrowRight' width={40} height={40} />
                    </CarouselNext>
                </Carousel>
            </div>
        </section>
    );
};

export default Section4;